config/routes.rb
KidsCodeCamp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'events#index'
  
  match 'about' => 'editpages#show',:defaults => {:id => 'about'}
  match 'tools' => 'editpages#show',:defaults => {:id => 'tools'}
  match 'lessons' => 'editpages#show',:defaults => {:id => 'lessons'}

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  # Devise
  devise_scope :user do
    match 'sign_up' => 'users/registrations#new'
    match 'login' => 'users/sessions#new'
    match 'logout' => 'users/sessions#destroy', :via => :delete
  end
  devise_for :users, :controllers => { :sessions => 'users/sessions', :registrations => 'users/registrations' }

  # Public
  resources :posts, :path => "community", :only => [:index]
  
  resources :categories, :path => "community", :only => [:index] do
    resources :posts, :path => "/"
  end

  scope :only => [:index, :show] do
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :content, :slug, :title

  validates :title, :length => { :in => 2..100 }, :presence => true
  validates :content, :presence => true

  extend FriendlyId
  friendly_id :title, :use => :slugged

  def self.get_paginated(page = 1)
    Event.paginate(page: page, per_page: 10).order('created_at DESC')
  end

  rails_admin do
    show do
      field :title
      field :content
      field :created_at
      field :updated_at
    end
    #=-=-=-=-=-=-=-=-=-=-
    list do
      field :title
      field :created_at
      field :updated_at
    end
    #=-=-=-=-=-=-=-=-=-=-
    edit do
      field :title
      field :content do
        html_attributes rows: 15, cols: 80
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.get_paginated(params[:page])
    @editpage = Editpage.get_page(:home)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.haml
- showing = action_name == 'show'
= link_to 'Back', root_path, :class => 'back' if showing
%article.preview.event
  %h3.title= showing ? event.title : link_to(event.title, event_path(event))
  %div.desc
    = markdown(event.content)
  %p.more= link_to 'Read more', event if !showing

app/views/events/_form.html.haml
= form_for [:admin,@event] do |f|
  - if @event.errors.any?
    #error_explanation
      %h2.title= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .input.text
    = f.label :title, "Title"
    = f.text_field :title

  .input.text
    = f.label :slug, "Slug"
    = f.text_field :slug

  .input.textarea
    = f.label :content, "Content"
    = f.text_area :content, :class => 'text_area'
    %p.legend= link_to 'Markdown is allowed', 'http://en.wikipedia.org/wiki/Markdown#Syntax_examples', :target => '_blank', :rel => 'nofollow'

  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
= link_to 'Back', events_path, :class => 'back'
%h1 Editing event
= render 'form'

app/views/events/index.html.haml
%div.session_links
  - flash.each do |name, msg|
    = content_tag :div, msg, :class => "flash_message #{name}" if msg.is_a?(String)

%section.desc
  = markdown(@editpage.content)

%section
  = render @events
  = will_paginate @events

  %p.suscribe-home
    %a.cta{:href=> "http://eepurl.com/u0LCj"} Subscribe to our Mailing List

app/views/events/new.html.haml
= link_to 'Back', events_path, :class => 'back'
%h1 New event
= render 'form'

app/views/events/show.html.haml
%h1.section-title Events
= render 'events/event', :event => @event