config/routes.rb
KidsCodeCamp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'events#index'
  
  match 'about' => 'editpages#show',:defaults => {:id => 'about'}
  match 'tools' => 'editpages#show',:defaults => {:id => 'tools'}
  match 'lessons' => 'editpages#show',:defaults => {:id => 'lessons'}

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  # Devise
  devise_scope :user do
    match 'sign_up' => 'users/registrations#new'
    match 'login' => 'users/sessions#new'
    match 'logout' => 'users/sessions#destroy', :via => :delete
  end
  devise_for :users, :controllers => { :sessions => 'users/sessions', :registrations => 'users/registrations' }

  # Public
  resources :posts, :path => "community", :only => [:index]
  
  resources :categories, :path => "community", :only => [:index] do
    resources :posts, :path => "/"
  end

  scope :only => [:index, :show] do
    resources :events
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :slug, :user_id, :parent_id, :category_id

  belongs_to :user
  belongs_to :category
  belongs_to :topic, :class_name => 'Post', :foreign_key => 'parent_id'
  has_many :responses, :class_name => 'Post', :foreign_key => 'parent_id', :dependent => :destroy
  
  validates :title, :length => { :in => 2..100 }, :presence => true, :unless => :parent_id?
  validates :category, :presence => true, :unless => :parent_id?
  validates :content, :user_id, :presence => true

  extend FriendlyId
  friendly_id :title, :use => :slugged

  def self.get_paginated_for_category(category, page = 1)
    Post.where({:parent_id => nil, :category_id => category}).paginate(:page => page, :per_page =>12).order('created_at DESC')
  end

  def self.get_paginated_for_topic(topic, page = 1)
    Post.where({:parent_id => topic}).paginate(:page => page, :per_page => 8).order("created_at")
  end

  # Rails Admin
  rails_admin do
    show do
      field :category
      field :title
      field :content
      field :user
      field :created_at
      field :updated_at
    end
    #=-=-=-=-=-=-=-=-=-=-=-=-=-
    list do
      field :title
      field :category
      field :user
      field :created_at
      field :updated_at
    end
    #=-=-=-=-=-=-=-=-=-=-=-=-=-
    edit do
      field :title
      field :content do
        html_attributes rows: 15, cols: 80
      end

      field :category do
        visible do
          bindings[:object].parent_id.blank?
        end
      end

      field :user do
        visible false
      end

      field :user_id, :hidden do
        visible true
        default_value do
          bindings[:view]._current_user.id
        end
      end
    end
    #=-=-=-=-=-=-=-=-=-=-=-=-=-
    update do
      configure :title do
        visible do
          bindings[:object].parent_id.blank?
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_filter :set_category
  # before_filter :check_category, only: [:new, :edit, :show, :create, :update]

  def index
    if params[:category_id].present?
      @posts = Post.get_paginated_for_category(Category.find(params[:category_id]), params[:page])
    else
      @posts = nil 
      @categories = Category.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
  
  
  def show
    @current_post = Post.find(params[:id])
    @posts = Post.get_paginated_for_topic(@current_post, params[:page])
    @post = Post.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
  
  
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end
  
  
  def edit
    @post = Post.find(params[:id])
  end
  
  
  def create
    params[:post][:user_id] = current_user.id if params[:post][:user_id].nil?
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to after_save_redirect(@post), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to after_save_redirect(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to after_delete_redirect(@post), notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end 
  

  def after_save_redirect(target)
    if target.parent_id.present? # Is a response
      target = target.topic
    end
    
    category_post_path(target.category,target)
  end
  

  def after_delete_redirect(target)
    if target.parent_id.present? # Is a response
      category_post_path(@post.topic.category,@post.topic)
    else
      category_posts_path(@post.category)
    end
  end


  def set_category
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.haml
- cancel_form_path = false

= form_for @post, :html => {:class => 'post_form'} do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :user_id, :value => current_user.id

  //// Dynamic inputs form logic
  - if action_name == 'show'
    = f.hidden_field :parent_id, {:value => params[:id]}
  - elsif @post.parent_id.present?
    = f.hidden_field :parent_id

  - if current_user.is_admin.zero? # Editor
    - if action_name != 'show'
      - if @post.parent_id.present? # Sub
        - cancel_form_path = post_path(@post.parent_id)
      - else # Main
        .input.select
          = f.label :category, "Category"
          = f.select :category, options_for_select(['General','Discussion','Teachers'])

        - if action_name == 'edit'
          - cancel_form_path = post_path(@post)
        - else
          - cancel_form_path = posts_path
  - else
    - cancel_form_path = rails_admin.index_path('posts')
    - if action_name != 'show' && @post.parent_id.blank? # new or edit main
      .input.select
        = f.label :category, "Category"
        = f.select :category, options_for_select(['General','Discussion','Teachers'])

  //// Static inputs
  .input.text
    = f.label :title, "Title"
    = f.text_field :title

  .input.textarea
    = f.label :content, "Content"
    = f.text_area :content

  .actions
    = f.submit('Post')
    - if cancel_form_path
      = raw ' or ' + link_to('Cancel', cancel_form_path)