config/routes.rb
KidsCodeCamp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'events#index'
  
  match 'about' => 'editpages#show',:defaults => {:id => 'about'}
  match 'tools' => 'editpages#show',:defaults => {:id => 'tools'}
  match 'lessons' => 'editpages#show',:defaults => {:id => 'lessons'}

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  # Devise
  devise_scope :user do
    match 'sign_up' => 'users/registrations#new'
    match 'login' => 'users/sessions#new'
    match 'logout' => 'users/sessions#destroy', :via => :delete
  end
  devise_for :users, :controllers => { :sessions => 'users/sessions', :registrations => 'users/registrations' }

  # Public
  resources :posts, :path => "community", :only => [:index]
  
  resources :categories, :path => "community", :only => [:index] do
    resources :posts, :path => "/"
  end

  scope :only => [:index, :show] do
    resources :events
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :slug, :user_id, :parent_id, :category_id

  belongs_to :user
  belongs_to :category
  belongs_to :topic, :class_name => 'Post', :foreign_key => 'parent_id'
  has_many :responses, :class_name => 'Post', :foreign_key => 'parent_id', :dependent => :destroy
  
  validates :title, :length => { :in => 2..100 }, :presence => true, :unless => :parent_id?
  validates :category, :presence => true, :unless => :parent_id?
  validates :content, :user_id, :presence => true

  extend FriendlyId
  friendly_id :title, :use => :slugged

  def self.get_paginated_for_category(category, page = 1)
    Post.where({:parent_id => nil, :category_id => category}).paginate(:page => page, :per_page =>12).order('created_at DESC')
  end

  def self.get_paginated_for_topic(topic, page = 1)
    Post.where({:parent_id => topic}).paginate(:page => page, :per_page => 8).order("created_at")
  end

  # Rails Admin
  rails_admin do
    show do
      field :category
      field :title
      field :content
      field :user
      field :created_at
      field :updated_at
    end
    #=-=-=-=-=-=-=-=-=-=-=-=-=-
    list do
      field :title
      field :category
      field :user
      field :created_at
      field :updated_at
    end
    #=-=-=-=-=-=-=-=-=-=-=-=-=-
    edit do
      field :title
      field :content do
        html_attributes rows: 15, cols: 80
      end

      field :category do
        visible do
          bindings[:object].parent_id.blank?
        end
      end

      field :user do
        visible false
      end

      field :user_id, :hidden do
        visible true
        default_value do
          bindings[:view]._current_user.id
        end
      end
    end
    #=-=-=-=-=-=-=-=-=-=-=-=-=-
    update do
      configure :title do
        visible do
          bindings[:object].parent_id.blank?
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_filter :set_category
  # before_filter :check_category, only: [:new, :edit, :show, :create, :update]

  def index
    if params[:category_id].present?
      @posts = Post.get_paginated_for_category(Category.find(params[:category_id]), params[:page])
    else
      @posts = nil 
      @categories = Category.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
  
  
  def show
    @current_post = Post.find(params[:id])
    @posts = Post.get_paginated_for_topic(@current_post, params[:page])
    @post = Post.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
  
  
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end
  
  
  def edit
    @post = Post.find(params[:id])
  end
  
  
  def create
    params[:post][:user_id] = current_user.id if params[:post][:user_id].nil?
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to after_save_redirect(@post), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to after_save_redirect(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to after_delete_redirect(@post), notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end 
  

  def after_save_redirect(target)
    if target.parent_id.present? # Is a response
      target = target.topic
    end
    
    category_post_path(target.category,target)
  end
  

  def after_delete_redirect(target)
    if target.parent_id.present? # Is a response
      category_post_path(@post.topic.category,@post.topic)
    else
      category_posts_path(@post.category)
    end
  end


  def set_category
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/.form.html.haml
= form_for @post do |f|
  .field
    = f.label :title, "SUBJECT"
    = f.text_field :title
  .field
    = f.label :body, "MESSAGE"
    = f.text_area :body, :size => "54x19"
  = f.hidden_field :parent_id
  .actions
    = f.submit "POST", :class => "contact-submit"

app/views/posts/_categories.html.haml
%tr
  %th Category
  /%th Created
  %th Topics
  %th Posts
  %th Last post by

- @categories.each do |category|
  - last_resp = category.posts.last
  %tr
    %td.categories_name
      %h3.title= link_to category.title, category_posts_path(category)
      .desc= category.description
    %td= category.posts.length
    %td= category.posts.length + category.responses.length
    %td
      - if last_resp
        #{last_resp.created_at.strftime("%a, %D %R")} by #{gravatar(last_resp.user,:size => '18')} #{content_tag('strong',last_resp.user.username)}
      - else
        \–

app/views/posts/_form.html.haml
- cancel_form_path = false
= form_for [@category, @post], :html => {:class => 'post_form'} do |f|
  - if @post.errors.any?
    #error_explanation
      %h2.title= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :user_id, :value => current_user.id

  //// Dynamic inputs form logic
  - if action_name == 'show'
    = f.hidden_field :parent_id, { :value => @current_post.id }
  - elsif @post.parent_id.present?
    = f.hidden_field :parent_id

  - if user_signed_in?
    - if action_name != 'show' # New/Edit Main or Edit Reponse
      - if @post.parent_id.present? # Edit Response
        - cancel_form_path = category_post_path(@category,@post.topic)
      - else # New/Edit Main
        - if @category.blank?
          .input.select
            = f.label :category, "Category"
            = f.collection_select :category_id, Category.all, :id, :title
        - else
          = f.hidden_field :category_id, :value => @category.id

        .input.text
          = f.label :title, "Title"
          = f.text_field :title

        - if action_name == 'edit' # Edit Main
          - cancel_form_path = category_post_path(@post.category, @post)
        - else # New Main
          - cancel_form_path = category_posts_path(@category)

  //// Static inputs

  .input.textarea
    - if action_name != 'show'
      = f.label :content, "Content"
    = f.text_area :content
    %p.legend= link_to 'Markdown is allowed', 'http://en.wikipedia.org/wiki/Markdown#Syntax_examples', :target => '_blank', :rel => 'nofollow'

  .actions
    = image_submit_tag "bt-submit.png"
    - if cancel_form_path
      = raw ' or ' + link_to('Cancel', cancel_form_path)

app/views/posts/_post.html.haml
- editable = user_signed_in? && (current_user.is_admin? || post.user_id == current_user.id) && action_name == 'show'
.topics
  .td.post_created #{gravatar(post.user, :size => 24)} Posted by #{content_tag('strong',post.user.username)} – #{post.created_at.strftime("%a, %b %e %Y at %R")}
  .td.post_content
    = markdown(post.content)
  - if editable
    .td.action
      = link_to('Edit', edit_category_post_path(@category,post)) + ' | '
      = link_to 'Destroy', {:category_id => @category, :id => post}, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/posts/_posts.html.haml
%tr
  %th Topic
  %th Created
  %th Replies
  %th Last post by

- @posts.each do |post|
  - last_resp = post.responses.last
  %tr
    %td
      %h3.title= link_to post.title, category_post_path(post.category,post)
      by #{gravatar(post.user,:size => '18')} #{content_tag('strong',post.user.username)}
    %td #{post.created_at.strftime("%a, %D %R")}
    %td #{post.responses.length}
    %td
      - if last_resp
        #{last_resp.created_at.strftime("%a, %D %R")} by #{content_tag('strong',last_resp.user.username)}
      - else
        \–

app/views/posts/_topic.html.haml
- editable = post.user_id == current_user.id && action_name == 'show'
%tr
  %td{rowspan:editable ? 3 :2}
  %td= "#{post.title} #{post.created_at.strftime("%d %b %y")}"
  %td= "#{post.title} #{post.created_at.strftime("%d %b %y")}"
  %td= "#{post.title} #{post.created_at.strftime("%d %b %y")}"

app/views/posts/create.html.haml
%h1 Posts#create
%p Find me in app/views/posts/create.html.haml

app/views/posts/destroy.html.haml
%h1 Posts#destroy
%p Find me in app/views/posts/destroy.html.haml

app/views/posts/edit.html.haml
- back_url = @post.parent_id.blank? ? category_post_path(@category,@post) : category_post_path(@category, @post.topic)
= link_to 'Back', back_url, :class => 'back'
%h1 Editing post
= render 'form'

app/views/posts/index.html.haml
= render :partial => "devise/session_links"
%h1.section-title Our Community
.community_controls
  - unless @posts.nil?
    = link_to 'New Post', {:action => 'new'}, :class => 'cta new_post_button'
    = link_to 'Categories', posts_path, :class => 'back'

.topics
  %table
    = render "posts/#{@posts.nil? ? 'categories' : 'posts'}"

- unless @posts.nil?
  = will_paginate @posts

app/views/posts/new.html.haml
- back_url = @category.blank? ? posts_path : category_posts_path
= link_to 'Back', back_url, :class => 'back'
%h1 New post

= render 'form'

app/views/posts/show.html.haml
= render :partial => "devise/session_links"
= link_to 'Back', {:action => 'index'}, :class => 'back'

%h2.blue-title.title= gravatar(@current_post.user, :size => 48) + content_tag('span',@current_post.title)
- if @current_post && (params[:page].blank? || params[:page] == 1)
  = render @current_post
- else
  %h3.title (Page #{params[:page]})
= render @posts

= will_paginate @posts

- if user_signed_in?
  #response_form
    %h3.title Add a response
    = render :partial => 'posts/form'
  

app/views/posts/update.html.haml
%h1 Posts#update
%p Find me in app/views/posts/update.html.haml