config/routes.rb
KidsCodeCamp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'events#index'
  
  match 'about' => 'editpages#show',:defaults => {:id => 'about'}
  match 'tools' => 'editpages#show',:defaults => {:id => 'tools'}
  match 'lessons' => 'editpages#show',:defaults => {:id => 'lessons'}

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  # Devise
  devise_scope :user do
    match 'sign_up' => 'users/registrations#new'
    match 'login' => 'users/sessions#new'
    match 'logout' => 'users/sessions#destroy', :via => :delete
  end
  devise_for :users, :controllers => { :sessions => 'users/sessions', :registrations => 'users/registrations' }

  # Public
  resources :posts, :path => "community", :only => [:index]
  
  resources :categories, :path => "community", :only => [:index] do
    resources :posts, :path => "/"
  end

  scope :only => [:index, :show] do
    resources :events
  end

end

app/views/layouts/_boards_top.html.haml
.rules
  %h3 Forum Rules
  %p Please read forum rules before you post.

= render :partial => "layouts/user_controls"

.clear

= form_tag("/search", :method => "get", :class => "search-forum") do
  = text_field_tag :search, params[:search], :class => "search-text"
  = image_submit_tag("magnifying-glass2.png", :class => "search-image")
.clear

app/views/layouts/_footer.html.haml
%footer
  %p
    %a{:href => "http://hybridgroup.com/"} The Hybrid Group
    %a.last{:href => "http://kidsruby.com/"} KidsRuby
  %p All Rights Reseved 2012-2013 The HybridGroup

app/views/layouts/_jsfooter.html.erb
<!-- UserVoice JavaScript SDK (only needed once on a page) -->
<script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/P89eET11aophvf6UPVoHWw.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>

<!-- A tab to launch the Classic Widget -->
<script>
UserVoice = window.UserVoice || [];
UserVoice.push(['showTab', 'classic_widget', {
  mode: 'full',
  primary_color: '#cc6d00',
  link_color: '#007dbf',
  default_mode: 'support',
  forum_id: 219808,
  tab_label: 'Feedback & Support',
  tab_color: '#cc6d00',
  tab_position: 'middle-left',
  tab_inverted: false
}]);
</script>

app/views/layouts/_sidebar.html.haml
%aside
  .pad
    .social
      = link_to "FOLLOWERS", "http://www.twitter.com/kidscodecamp"
      = link_to "FANS", "https://www.facebook.com/Kidscodecamp"
    %form#signup{:action => 'http://kanbanpad.us2.list-manage1.com/subscribe/post', :method => 'POST'}
      %p Subscribe to our newsletter to receive the latests news about KidsCodeCamp
      %input{:autocapitalize => "off", :autocorrect => "off", :name => "MERGE0", :type => "text", :value => ""}
      %input{:name => "u", :type => "hidden", :value => "281b52acbc791fcbe2127e282"}
      %input{:name => "id", :type => "hidden", :value => "67c6dbfbd1"}
      = image_submit_tag "bt-send.png"
    .twitter-widget
      %h3 KIDSCODECAMP on Twitter
      #tweets
        %a.twitter-timeline{:href => 'https://twitter.com/KidsCodeCamp', :'data-widget-id' => '350766064952569856' } Tweets por @KidsCodeCamp
        %script !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

    .sponsors
      %p KidsCodeCamp is created by:
      = link_to image_tag("logo-bw-hybrid.png"), "http://hybridgroup.com/"
      %p KidsCodeCamp is brought to you by:
      = link_to image_tag("logo-retreat.png"), "http://coderetreat.org"
      = link_to image_tag("logo-att.png",:class => 'white-bg'), "http://www.att.com/"
      = link_to image_tag("logo-engineyard-horizontal.png",:class => 'white-bg'), "https://www.engineyard.com/"
      = link_to image_tag("logo-sphero.png",:class => 'white-bg'), "http://www.gosphero.com/"
      = link_to image_tag("logo-famigo.png",:class => 'white-bg'), "http://www.famigo.com/"
      = link_to image_tag("logo-ruby-central.png"), "http://rubycentral.org/"

app/views/layouts/_user_controls.html.haml
- if current_user
  .user-controls
    %p= "Welcome #{current_user.username}!"
    = link_to "Profile", edit_user_registration_path(current_user.id)
    = link_to "Logout", destroy_user_session_path, :method => :delete
- else
  .user-controls
    %p= "Welcome!"
    = link_to "Register", new_user_registration_path
    = link_to "Login", new_user_session_path

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Administrative Panel
    = stylesheet_link_tag    "admin/admin", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render partial: "devise/session_links"
    = render partial: "admin/menu"
    %h1 Administrative Panel
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title KidsCodeCamp - Teaching The Kids of Planet Earth To Code
    = favicon_link_tag "/favicon.ico?1"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "jquery.tweetable.js"
    = csrf_meta_tags
  %body{class: "c-#{params[:controller]} a-#{params[:action]}"}
    #page
      %header
        %h1#logo
          = link_to('',root_path, :title => 'KidsCodeCamp - Teaching The Kids of Planet Earth To Code')
      %nav
        %ul
          %li= link_to "Home", root_path
          %li= link_to "About", about_path
          %li= link_to "Tools & Toys", tools_path
          %li= link_to "Lessons", lessons_path
          %li= link_to "Community", posts_path(:category => nil)
          %li= link_to "Contact Us", contact_path
      %section#page-body
        %section.content
          .pad= yield
        = render :partial => "layouts/sidebar"
      = render :partial => "layouts/footer"

  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-39441624-1']);
    _gaq.push(['_setDomainName', 'none' 'kidscodecamp.com']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  = render partial: 'layouts/jsfooter'

app/views/layouts/member.html.haml
!!!
%html
  %head
    %title Member Panel
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render partial: "devise/session_links"
    %h1 Member Panel
    = yield